site_name: GOTO Toastmasters 
site_description: 'A website for the Melbourne, AU based Toastmasters group'
site_author: 'Rob Kenefeck'
site_url: 'https://www.kenefeck.com/GOTO' # Uncomment to set a canonical URL

copyright: |
  &copy; The information on this website is for the sole use of Toastmasters' members, for Toastmasters business only. It is not to be used for solicitation and distribution of non-Toastmasters material or information. All rights reserved. Toastmasters International, the Toastmasters International logo and all other Toastmasters International trademarks and copyrights are the sole property of Toastmasters International and may be used only by permission.
docs_dir: docs/
nav:
  - Welcome: index.md
  - The Pitch: pitch.md
  - Roles: roles.md
  - Events: events.md
theme:
  name: 'material'
  palette:
    scheme: 'slate'
    primary: 'custom'
    accent: 'custom'
  features:
  - navigation.tabs        # Render top sections as tabs at the top.
  - navigation.tabs.sticky # Tabs won't disappear when scrolling down. Requires "navigation.tabs".
  - navigation.top         # Adds a "Back to top" that is shown when scrolling up.
  - navigation.tracking    # Updates the url with highlighted section anchor.
  - toc.integrate          # Include the TOC sections in the left navugation.
  logo: "https://ccdn.toastmasters.org/medias/files/brand-materials/loyal-blue-masthead-logo.png"
  icon:
    logo: 'material/library'
    repo: 'material/library'
  font: Montserrat
extra:
  social:
    - icon: 'fontawesome/brands/linkedin'
      link: 'https://www.linkedin.com/company/goto-toastmasters'
markdown_extensions:
  - markdown.extensions.admonition:
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.toc:
      permalink: true
plugins:
  - privacy