site_name: GOTO Toastmasters 
site_description: 'A website for the Melbourne, AU based Toastmasters group'
site_author: 'Rob Kenefeck'
site_url: 'https://www.kenefeck.com/GOTO' # Uncomment to set a canonical URL

copyright: |
  &copy; Author
docs_dir: docs/
nav:
  - Welcome: index.md
  - About: about.md
  - The Pitch: pitch.md
  - Roles: roles.md
  - Events: events.md
theme:
  name: 'material'
  palette:
    scheme: 'slate'
    primary: 'loyalblue'
    accent: 'loyalblue'
  features:
  - navigation.tabs        # Render top sections as tabs at the top.
  - navigation.tabs.sticky # Tabs won't disappear when scrolling down. Requires "navigation.tabs".
  - navigation.top         # Adds a "Back to top" that is shown when scrolling up.
  - navigation.tracking    # Updates the url with highlighted section anchor.
  - toc.integrate          # Include the TOC sections in the left navugation.
  logo: "https://ccdn.toastmasters.org/medias/files/brand-materials/loyal-blue-masthead-logo.png"
  icon:
    logo: 'material/library'
    repo: 'material/library'
extra:
  social:
    - icon: 'fontawesome/brands/linkedin'
      link: 'https://www.linkedin.com/company/goto-toastmasters'
markdown_extensions:
  - markdown.extensions.admonition:
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.toc:
      permalink: true